// team-ui/src/components/TagManager.svelte
<script lang="ts">
  import type { Tag } from '$lib/types';
  import { api } from '$lib/api';

  let {
    tags,
    onMerged,
  }: {
    tags: Tag[];
    onMerged?: () => void;
  } = $props();

  let expanded = $state(false);
  let mergingTagId = $state<string | null>(null);
  let mergeTargetId = $state<string>('');
  let merging = $state(false);
  let mergeError = $state('');

  function startMerge(tagId: string) {
    mergingTagId = tagId;
    mergeTargetId = '';
    mergeError = '';
  }

  function cancelMerge() {
    mergingTagId = null;
    mergeTargetId = '';
    mergeError = '';
  }

  async function confirmMerge() {
    if (!mergingTagId || !mergeTargetId) return;
    merging = true;
    mergeError = '';
    try {
      await api.mergeTags(mergingTagId, mergeTargetId);
      mergingTagId = null;
      mergeTargetId = '';
      onMerged?.();
    } catch (e) {
      mergeError = e instanceof Error ? e.message : 'Merge failed';
    } finally {
      merging = false;
    }
  }

  const otherTags = $derived(tags.filter(t => t.id !== mergingTagId));
</script>

<div class="bg-white rounded-xl border border-gray-200 overflow-hidden">
  <button
    onclick={() => (expanded = !expanded)}
    class="w-full flex items-center justify-between px-5 py-4 hover:bg-gray-50 transition-colors"
  >
    <div class="flex items-center gap-2">
      <svg class="w-4 h-4 text-gray-500" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M17.707 9.293a1 1 0 010 1.414l-7 7a1 1 0 01-1.414 0l-7-7A.997.997 0 012 10V5a3 3 0 013-3h5c.256 0 .512.098.707.293l7 7zM5 6a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd" />
      </svg>
      <h3 class="text-sm font-semibold text-gray-900">Tag Manager</h3>
      <span class="text-xs text-gray-500">({tags.length} tags)</span>
    </div>
    <svg
      class="w-4 h-4 text-gray-400 transition-transform {expanded ? 'rotate-180' : ''}"
      viewBox="0 0 20 20"
      fill="currentColor"
    >
      <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
    </svg>
  </button>

  {#if expanded}
    <div class="border-t border-gray-100 divide-y divide-gray-50">
      {#each tags as tag}
        <div class="px-5 py-3 flex items-center justify-between gap-3">
          <div class="flex items-center gap-2">
            <span class="text-sm font-medium text-gray-800">{tag.name}</span>
            <span class="text-xs text-gray-400">{tag.usage_count} uses</span>
          </div>

          {#if mergingTagId === tag.id}
            <div class="flex items-center gap-2">
              <select
                bind:value={mergeTargetId}
                class="text-xs border border-gray-300 rounded px-2 py-1 text-gray-700 focus:outline-none focus:ring-1 focus:ring-indigo-500"
              >
                <option value="">Merge into…</option>
                {#each otherTags as other}
                  <option value={other.id}>{other.name}</option>
                {/each}
              </select>
              <button
                onclick={confirmMerge}
                disabled={!mergeTargetId || merging}
                class="text-xs px-2 py-1 bg-indigo-600 text-white rounded hover:bg-indigo-700 disabled:opacity-40 transition-colors"
              >
                {merging ? '…' : 'Merge'}
              </button>
              <button
                onclick={cancelMerge}
                class="text-xs px-2 py-1 text-gray-500 hover:text-gray-700 transition-colors"
              >
                Cancel
              </button>
            </div>
          {:else}
            <button
              onclick={() => startMerge(tag.id)}
              class="text-xs text-gray-400 hover:text-indigo-600 transition-colors"
            >
              Merge into…
            </button>
          {/if}
        </div>
        {#if mergingTagId === tag.id && mergeError}
          <p class="px-5 pb-2 text-xs text-red-600">{mergeError}</p>
        {/if}
      {/each}
    </div>
  {/if}
</div>

// team-ui-react/src/components/TagManager.tsx
import { useState } from "react";
import { api } from "../api";
import type { Tag } from "../types";

interface Props {
  tags: Tag[];
  onRefresh: () => void;
}

export function TagManager({ tags, onRefresh }: Props) {
  const [open, setOpen] = useState(false);
  const [mergingTagId, setMergingTagId] = useState<string | null>(null);
  const [targetTagId, setTargetTagId] = useState<string>("");
  const [merging, setMerging] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleMerge(sourceId: string) {
    if (!targetTagId || targetTagId === sourceId) return;
    setMerging(true);
    setError(null);
    try {
      await api.mergeTags(sourceId, targetTagId);
      setMergingTagId(null);
      setTargetTagId("");
      onRefresh();
    } catch {
      setError("Merge failed — try again");
    } finally {
      setMerging(false);
    }
  }

  const sorted = [...tags].sort((a, b) => b.usage_count - a.usage_count);

  return (
    <div className="bg-white rounded-lg border border-gray-200">
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between px-4 py-3 text-left"
      >
        <h3 className="text-xs font-semibold text-gray-500 uppercase">
          Tags ({tags.length})
        </h3>
        <span className="text-gray-400 text-sm">{open ? "▲" : "▼"}</span>
      </button>

      {open && (
        <div className="px-4 pb-4">
          {error && (
            <p className="text-sm text-red-600 mb-3">{error}</p>
          )}
          <div className="space-y-2 max-h-64 overflow-y-auto">
            {sorted.map((tag) => (
              <div key={tag.id} className="flex items-center gap-2">
                <span className="flex-1 text-sm text-gray-700 truncate">
                  {tag.name}
                  <span className="ml-1.5 text-xs text-gray-400">({tag.usage_count})</span>
                </span>

                {mergingTagId === tag.id ? (
                  <div className="flex items-center gap-1">
                    <select
                      value={targetTagId}
                      onChange={(e) => setTargetTagId(e.target.value)}
                      className="text-xs border border-gray-300 rounded px-1 py-0.5"
                      disabled={merging}
                    >
                      <option value="">Merge into...</option>
                      {sorted
                        .filter((t) => t.id !== tag.id)
                        .map((t) => (
                          <option key={t.id} value={t.id}>
                            {t.name}
                          </option>
                        ))}
                    </select>
                    <button
                      onClick={() => handleMerge(tag.id)}
                      disabled={merging || !targetTagId}
                      className="text-xs font-medium text-indigo-600 hover:text-indigo-800 disabled:opacity-50"
                    >
                      {merging ? "..." : "Go"}
                    </button>
                    <button
                      onClick={() => { setMergingTagId(null); setTargetTagId(""); }}
                      className="text-xs text-gray-400 hover:text-gray-600"
                    >
                      Cancel
                    </button>
                  </div>
                ) : (
                  <button
                    onClick={() => setMergingTagId(tag.id)}
                    className="text-xs text-gray-400 hover:text-indigo-600"
                  >
                    Merge
                  </button>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
