// team-ui/src/components/ReviewCard.tsx
import { forwardRef, useState } from "react";
import Markdown from "react-markdown";
import type { ReviewItem, Selection } from "../types";
import { EditModal } from "./EditModal";
import { timeAgo } from "../utils";
import { api } from "../api";
import type { DragState, PointerHandlers } from "../hooks/useCardDrag";
import { FLY_OFF_MS, MAX_ROTATION_DEG, SNAP_BACK_MS } from "../hooks/useCardDrag";

interface Props {
  item: ReviewItem;
  selection: Selection;
  drag: DragState;
  pointerHandlers: PointerHandlers;
  onContentEdited?: (newBody: string) => void;
}

const CARD_STYLES: Record<string, string> = {
  neutral: "border-gray-200 bg-white",
  approve: "border-green-300 bg-green-50",
  reject: "border-red-300 bg-red-50",
  skip: "border-slate-400 bg-slate-50",
};

export const ReviewCard = forwardRef<HTMLDivElement, Props>(
  function ReviewCard({ item, selection, drag, pointerHandlers, onContentEdited }, ref) {
    const [editOpen, setEditOpen] = useState(false);

    const activeState = drag.isDragging || drag.isFlyingOff ? drag.dragAction : selection;
    const cardStyle = CARD_STYLES[activeState ?? "neutral"];

    const rotation = drag.isDragging
      ? (drag.offset.x / 300) * MAX_ROTATION_DEG
      : 0;
    const shadowScale = drag.isDragging ? 1 + drag.dragProgress * 0.5 : 1;
    const transform = `translate(${drag.offset.x}px, ${drag.offset.y}px) rotate(${rotation}deg)`;
    const transition = drag.isDragging
      ? "none"
      : drag.isFlyingOff
        ? `transform ${FLY_OFF_MS}ms ease-in, box-shadow ${FLY_OFF_MS}ms ease-in`
        : `transform ${SNAP_BACK_MS}ms ease-out, box-shadow ${SNAP_BACK_MS}ms ease-out`;
    const shadow = `0 ${4 * shadowScale}px ${20 * shadowScale}px rgba(0,0,0,${0.08 * shadowScale})`;

    const { question, content, type } = item;
    const contentBody = content.body;

    async function handleSave(newBody: string) {
      if (type === "answer") {
        await api.editAnswer(content.id, newBody);
      } else {
        await api.editAnswer(content.id, newBody);
      }
      onContentEdited?.(newBody);
    }

    const isSupervised = "supervised" in content && content.supervised;

    return (
      <>
        <div
          ref={ref}
          className={`relative z-0 border-2 rounded-lg p-5 max-w-xl mx-auto select-none touch-none ${cardStyle}`}
          style={{ transform, transition, boxShadow: shadow }}
          {...pointerHandlers}
        >
          {/* Question context */}
          <div className="mb-4">
            <div className="flex items-start justify-between gap-2 mb-1">
              <h2 className="text-base font-semibold text-gray-900 leading-snug">
                {question.title}
              </h2>
              <span className="shrink-0 text-xs text-gray-400 whitespace-nowrap">
                {timeAgo(question.created_at)}
              </span>
            </div>

            {question.tags && question.tags.length > 0 && (
              <div className="flex flex-wrap gap-1 mb-2">
                {question.tags.map((tag) => (
                  <span
                    key={tag.id ?? tag.name}
                    className="inline-block rounded-full bg-indigo-50 px-2 py-0.5 text-xs font-medium text-indigo-700"
                  >
                    {tag.name}
                  </span>
                ))}
              </div>
            )}

            {question.body && (
              <div className="mt-2 text-sm text-gray-500 leading-relaxed line-clamp-3 prose prose-sm prose-gray max-w-none">
                <Markdown>{question.body}</Markdown>
              </div>
            )}
          </div>

          <div className="border-t border-gray-200 my-3" />

          {/* Item under review */}
          <div className="relative">
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <span className="text-xs font-semibold text-gray-500 uppercase tracking-wide">
                  {type === "answer" ? "Answer" : "Comment"}
                </span>
                {isSupervised && (
                  <span className="inline-block rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700">
                    supervised
                  </span>
                )}
              </div>
              <div className="flex items-center gap-2">
                <button
                  onPointerDown={(e) => e.stopPropagation()}
                  onClick={(e) => {
                    e.stopPropagation();
                    setEditOpen(true);
                  }}
                  className="text-xs text-indigo-500 hover:text-indigo-700 font-medium"
                >
                  Edit
                </button>
              </div>
            </div>

            <div className="text-sm text-gray-800 leading-relaxed prose prose-sm max-w-none prose-headings:text-gray-900 prose-code:bg-gray-100 prose-code:px-1 prose-code:rounded prose-pre:bg-gray-50 prose-pre:border prose-pre:border-gray-200">
              <Markdown>{contentBody}</Markdown>
            </div>

            <p className="mt-2 text-xs text-gray-400">
              by {content.created_by} ({content.created_by_type}) · {timeAgo(content.created_at)}
            </p>
          </div>
        </div>

        <EditModal
          isOpen={editOpen}
          onClose={() => setEditOpen(false)}
          onSave={handleSave}
          title={`Edit ${type}`}
          initialBody={contentBody}
        />
      </>
    );
  },
);

// team-ui/src/components/ReviewCard.svelte
<script lang="ts">
  import type { ReviewItem, Answer } from '$lib/types';
  import { timeAgo } from '$lib/utils';
  import Markdown from './Markdown.svelte';
  import EditModal from './EditModal.svelte';
  import { api } from '$lib/api';

  let {
    item,
    onEditSaved,
  }: {
    item: ReviewItem;
    onEditSaved?: () => void;
  } = $props();

  let questionExpanded = $state(false);
  let showEditModal = $state(false);

  const isAnswer = $derived(item.type === 'answer');
  const content = $derived(item.content);
  const answer = $derived(isAnswer ? item.content as Answer : null);

  async function saveEdit(body: string) {
    if (isAnswer) {
      await api.editAnswer(item.content.id, body);
    }
    onEditSaved?.();
  }
</script>

<div class="max-w-2xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-200 overflow-hidden">
  <!-- Question context (collapsible) -->
  <div class="border-b border-gray-100">
    <button
      onclick={() => (questionExpanded = !questionExpanded)}
      class="w-full text-left px-6 py-4 hover:bg-gray-50 transition-colors group"
    >
      <div class="flex items-start justify-between gap-3">
        <div class="flex-1 min-w-0">
          <p class="text-xs font-medium text-gray-400 uppercase tracking-wide mb-1">Question</p>
          <h3 class="text-base font-semibold text-gray-900 leading-snug">{item.question.title}</h3>
          {#if item.question.tags && item.question.tags.length > 0}
            <div class="flex flex-wrap gap-1.5 mt-2">
              {#each item.question.tags as tag}
                <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs bg-indigo-50 text-indigo-700 font-medium">
                  {tag.name}
                </span>
              {/each}
            </div>
          {/if}
          {#if !questionExpanded}
            <p class="text-xs text-gray-400 mt-1.5 group-hover:text-gray-500 transition-colors">
              click to expand
            </p>
          {/if}
        </div>
        <svg
          class="w-4 h-4 text-gray-400 flex-shrink-0 mt-1 transition-transform {questionExpanded ? 'rotate-180' : ''}"
          viewBox="0 0 20 20"
          fill="currentColor"
        >
          <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
        </svg>
      </div>
    </button>

    {#if questionExpanded}
      <div class="px-6 pb-4">
        <Markdown content={item.question.body} />
      </div>
    {/if}
  </div>

  <!-- Answer/comment body -->
  <div class="px-6 py-5">
    <div class="flex items-center justify-between mb-3">
      <div class="flex items-center gap-2">
        <p class="text-xs font-medium text-indigo-600 uppercase tracking-wide">
          {isAnswer ? 'Answer for review' : 'Comment for review'}
        </p>
        {#if answer?.supervised}
          <span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-700">
            supervised
          </span>
        {/if}
      </div>
      <button
        onclick={() => (showEditModal = true)}
        class="text-xs text-indigo-600 hover:text-indigo-800 font-medium transition-colors hover:underline"
      >
        Edit before approving
      </button>
    </div>

    <Markdown content={content.body} />
  </div>

  <!-- Footer -->
  <div class="px-6 py-3 bg-gray-50 border-t border-gray-100 flex items-center justify-between">
    <span class="text-xs text-gray-500">
      by <span class="font-medium text-gray-700">{content.created_by}</span>
      <span class="text-gray-400">({content.created_by_type})</span>
    </span>
    <span class="text-xs text-gray-400">{timeAgo(content.created_at)}</span>
  </div>
</div>

{#if showEditModal}
  <EditModal
    title="Edit {isAnswer ? 'answer' : 'comment'}"
    initialBody={content.body}
    onSave={saveEdit}
    onClose={() => (showEditModal = false)}
  />
{/if}
