// team-ui/src/components/VoteBadge.svelte
<script lang="ts">
  let {
    agent_upvotes = 0,
    agent_downvotes = 0,
    human_upvotes = 0,
    human_downvotes = 0,
  }: {
    agent_upvotes?: number;
    agent_downvotes?: number;
    human_upvotes?: number;
    human_downvotes?: number;
  } = $props();
</script>

<span class="inline-flex items-center gap-2 text-xs text-gray-500">
  <span class="flex items-center gap-0.5">
    <span class={agent_upvotes > 0 ? 'text-green-600' : 'text-gray-400'}>{agent_upvotes}↑</span>
    <span class={agent_downvotes > 0 ? 'text-red-500' : 'text-gray-400'}>{agent_downvotes}↓</span>
    <span class="text-gray-400">(agent)</span>
  </span>
  <span class="text-gray-300">·</span>
  <span class="flex items-center gap-0.5">
    <span class={human_upvotes > 0 ? 'text-green-600' : 'text-gray-400'}>{human_upvotes}↑</span>
    <span class={human_downvotes > 0 ? 'text-red-500' : 'text-gray-400'}>{human_downvotes}↓</span>
    <span class="text-gray-400">(human)</span>
  </span>
</span>

// team-ui/src/components/VoteBadge.tsx
import type { VoteCounts } from "../types";

function VoteGroup({
  upvotes,
  downvotes,
  label,
}: {
  upvotes: number;
  downvotes: number;
  label: string;
}) {
  return (
    <span className="inline-flex items-center gap-1 text-xs">
      <span className={upvotes > 0 ? "text-green-600 font-medium" : "text-gray-400"}>
        {upvotes}↑
      </span>
      <span className={downvotes > 0 ? "text-red-600 font-medium" : "text-gray-400"}>
        {downvotes}↓
      </span>
      <span className="text-gray-400">({label})</span>
    </span>
  );
}

export function VoteBadge(votes: VoteCounts) {
  return (
    <span className="inline-flex items-center gap-2">
      <VoteGroup
        upvotes={votes.agent_upvotes}
        downvotes={votes.agent_downvotes}
        label="agent"
      />
      <span className="text-gray-300">·</span>
      <VoteGroup
        upvotes={votes.human_upvotes}
        downvotes={votes.human_downvotes}
        label="human"
      />
    </span>
  );
}
